import os
import sys

# 🚨 THE FIX: Must be at the absolute top before any 'agents' or 'orchestrator' imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from pymongo import MongoClient
from dotenv import load_dotenv
from orchestrator.langgraph_dag import SupervisoryOrchestrator

# 1. Connect to DB
load_dotenv()
client = MongoClient(
    os.getenv("MONGO_URI"), 
    serverSelectionTimeoutMS=5000,
    tls=True,
    tlsAllowInvalidCertificates=True 
)
db_collection = client["Stock_data"]["ticker"]

# 2. Initialize the fully integrated LangGraph Orchestrator
orchestrator = SupervisoryOrchestrator(db_collection)

# 3. Fire the System (2008 Crash Scenario)
final_state = orchestrator.run_monthly_cycle(universe_id="U1", target_date="2008-10-15")

# 4. Print the final results!
print("📊 FINAL BLACKBOARD MEMORY STATE:")
print(f"-> Instability Index: {final_state['instability_index']:.4f}")
print(f"-> Penalty Applied (λ_t): {final_state['lambda_t']:.4f}")

print("\n✅ SECURED PORTFOLIO WEIGHTS:")
weights = final_state['optimal_weights']
print(weights[weights > 0.0].sort_values(ascending=False).to_string())

print("\n" + "="*60)
print("📄 GENERATED HITL SUPERVISORY GOVERNANCE REPORT (Qwen 2.5)")
print("="*60)
# Print the report generated by local Ollama
print(final_state.get('hitl_report', "No report generated (Calm Market)."))
print("="*60 + "\n")