from __future__ import annotations

import os
import re
from typing import Any


CHART_TIER_FREE = "free"
CHART_TIER_PRO = "pro"
CHART_TIER_PREMIUM = "premium"


def _chart(
    *,
    chart_tier: str = CHART_TIER_FREE,
    component: str = "BarChart",
    chart_type: str = "bar",
    requires_premium: bool = False,
    required_fields: list[str] | None = None,
    fallback_chart: str | None = None,
    **extra: Any,
) -> dict[str, Any]:
    return {
        "chart_tier": chart_tier,
        "component": component,
        "chart_type": chart_type,
        "requires_premium": requires_premium,
        "required_fields": list(required_fields or []),
        "fallback_chart": fallback_chart,
        **extra,
    }


CHART_REGISTRY: dict[str, dict[str, Any]] = {
    "ticker_concentration_plot": _chart(required_fields=["ticker", "allocation_percent"]),
    "sector_concentration_plot": _chart(required_fields=["sector", "allocation_percent"]),
    "hhi_concentration_index": _chart(required_fields=["portfolio", "hhi_value"]),
    "effective_number_of_holdings": _chart(required_fields=["portfolio", "effective_count"]),
    "current_vs_advisory_allocation_by_ticker": _chart(
        required_fields=["ticker", "current_allocation_percent", "advisory_allocation_percent"]
    ),
    "allocation_change_by_ticker": _chart(required_fields=["ticker", "allocation_change_percent"]),
    "risk_contribution_by_ticker": _chart(required_fields=["ticker", "risk_contribution_percent"]),
    "return_range_by_ticker": _chart(
        chart_tier=CHART_TIER_PREMIUM,
        component="BarChartPremium",
        chart_type="rangeBar",
        requires_premium=True,
        required_fields=["ticker", "min_return", "max_return"],
        fallback_chart="standard_min_max_bar",
        range_start_field="min_return",
        range_end_field="max_return",
    ),
    "volatility_range_by_ticker": _chart(
        chart_tier=CHART_TIER_PREMIUM,
        component="BarChartPremium",
        chart_type="rangeBar",
        requires_premium=True,
        required_fields=["ticker", "min_volatility", "max_volatility"],
        fallback_chart="standard_min_max_bar",
        range_start_field="min_volatility",
        range_end_field="max_volatility",
    ),
    "portfolio_return_waterfall": _chart(
        chart_tier=CHART_TIER_PREMIUM,
        component="BarChartPremium",
        chart_type="rangeBar",
        requires_premium=True,
        required_fields=["component", "start_value", "end_value"],
        fallback_chart="contribution_bar",
        range_start_field="start_value",
        range_end_field="end_value",
    ),
    "risk_contribution_waterfall": _chart(
        chart_tier=CHART_TIER_PREMIUM,
        component="BarChartPremium",
        chart_type="rangeBar",
        requires_premium=True,
        required_fields=["component", "start_value", "end_value"],
        fallback_chart="contribution_bar",
        range_start_field="start_value",
        range_end_field="end_value",
    ),
    "current_vs_advisory_mirrored_bar": _chart(
        chart_tier=CHART_TIER_PREMIUM,
        component="BarChartPremium",
        chart_type="mirroredBar",
        requires_premium=True,
        required_fields=["ticker", "current_weight", "advisory_weight"],
        fallback_chart="grouped_bar",
    ),
    "return_distribution_histogram": _chart(
        chart_type="histogram",
        required_fields=["bin_start", "bin_end", "count"],
    ),
    "historical_adjusted_close": _chart(
        component="LineChart",
        chart_type="line",
        required_fields=["date", "adjusted_close"],
        required_context=["ticker"],
        fallback_computation="fetch_adjusted_close_history",
        allowed_intents=["plot_only", "data_exploration", "eda"],
        blocked_intents=["advisory_allocation", "optimization"],
    ),
    "normalized_price_comparison": _chart(
        component="LineChart",
        chart_type="line",
        required_fields=["date", "ticker", "normalized_price"],
        required_context=["tickers"],
        fallback_computation="normalize_adjusted_close_to_100",
        allowed_intents=["plot_only", "data_exploration", "eda"],
        blocked_intents=["advisory_allocation", "optimization"],
    ),
    "portfolio_value_over_time": _chart(
        component="LineChart",
        chart_type="line",
        required_fields=["date", "portfolio_value"],
        required_context=["weights", "initial_capital"],
        fallback_computation="compute_portfolio_value_from_weights",
        blocked_intents=["data_quality_only"],
    ),
    "drawdown_over_time": _chart(
        component="LineChart",
        chart_type="line_area",
        required_fields=["date", "drawdown_percent"],
        required_context=["weights"],
        fallback_computation="compute_drawdown_from_portfolio_value",
    ),
    "rolling_volatility_over_time": _chart(
        component="LineChart",
        chart_type="line",
        required_fields=["date", "rolling_volatility_percent"],
        fallback_computation="compute_rolling_volatility_from_returns",
    ),
    "rolling_correlation_over_time": _chart(
        component="LineChart",
        chart_type="line",
        required_fields=["date", "average_correlation"],
        fallback_computation="compute_rolling_average_correlation",
    ),
    "instability_index_over_time": _chart(
        chart_tier=CHART_TIER_PREMIUM,
        component="ChartsDataProviderPro",
        chart_type="line",
        requires_premium=True,
        required_fields=["date", "instability_index"],
        optional_fields=["calm_threshold", "crisis_threshold", "stress_bands"],
        fallback_chart="basic_instability_line",
        fallback_computation="compute_instability_index_if_components_available",
        allowed_intents=["instability_regime", "plot_only"],
        blocked_intents=["advisory_allocation", "optimization"],
    ),
    "cvar_over_time": _chart(
        component="LineChart",
        chart_type="line",
        required_fields=["date", "cvar_95"],
        required_context=["weights"],
        fallback_computation="compute_rolling_var_cvar",
    ),
    "governance_metric_threshold_over_time": _chart(
        component="LineChart",
        chart_type="line",
        required_fields=["date", "metric_value"],
        optional_fields=["threshold_value", "threshold_label"],
        fallback_computation="compute_governance_metric_threshold_series",
        allowed_intents=["plot_only", "risk_governance", "instability_regime"],
        blocked_intents=["advisory_allocation", "optimization"],
    ),
    "sector_allocation_donut": _chart(
        component="PieChart",
        chart_type="donut",
        required_fields=["sector", "weight_percent"],
        required_context=["sector_weights"],
        fallback_computation="compute_sector_weights_from_ticker_weights",
        allowed_intents=["plot_only", "diversification", "risk_governance"],
        blocked_intents=["time_series", "advisory_allocation", "optimization"],
        fallback_chart="sector_allocation_bar",
        category_field="sector",
        value_field="weight_percent",
        max_slices=8,
    ),
    "ticker_allocation_donut": _chart(
        component="PieChart",
        chart_type="donut",
        required_fields=["ticker", "weight_percent"],
        required_context=["ticker_weights"],
        allowed_intents=["plot_only", "diversification"],
        blocked_intents=["time_series", "advisory_allocation", "optimization"],
        fallback_chart="ticker_concentration_bar",
        category_field="ticker",
        value_field="weight_percent",
        max_slices=8,
    ),
    "risk_contribution_donut": _chart(
        component="PieChart",
        chart_type="donut",
        required_fields=["name", "risk_contribution_percent"],
        required_context=["weights", "covariance_matrix"],
        fallback_computation="compute_risk_contribution_from_weights_and_covariance",
        allowed_intents=["plot_only", "risk_governance"],
        blocked_intents=["time_series", "advisory_allocation", "optimization"],
        fallback_chart="risk_contribution_bar",
        category_field="name",
        value_field="risk_contribution_percent",
        max_slices=10,
    ),
    "sector_ticker_nested_donut": _chart(
        component="PieChart",
        chart_type="nested_donut",
        required_fields=["sector", "sector_weight_percent", "ticker", "ticker_weight_percent"],
        required_context=["ticker_weights", "sector_mapping"],
        fallback_computation="compute_sector_ticker_nested_donut",
        allowed_intents=["plot_only", "diversification"],
        blocked_intents=["time_series", "advisory_allocation", "optimization"],
        fallback_chart="sector_and_ticker_bar_group",
        category_field="ticker",
        value_field="ticker_weight_percent",
        max_inner_slices=8,
        max_outer_slices=25,
    ),
    "portfolio_health_donut": _chart(
        component="PieChart",
        chart_type="center_label_donut",
        required_fields=["health_component", "score"],
        required_context=["ticker_weights", "sector_mapping"],
        fallback_computation="compute_portfolio_health_components",
        allowed_intents=["plot_only", "diversification", "risk_governance", "instability_regime"],
        blocked_intents=["time_series", "advisory_allocation", "optimization"],
        category_field="health_component",
        value_field="score",
        max_slices=6,
    ),
    "semi_donut_risk_gauge": _chart(
        component="PieChart",
        chart_type="semi_donut",
        required_fields=["health_component", "score"],
        required_context=["ticker_weights", "sector_mapping"],
        fallback_computation="compute_portfolio_health_components",
        allowed_intents=["plot_only", "risk_governance", "instability_regime"],
        blocked_intents=["time_series", "advisory_allocation", "optimization"],
        category_field="health_component",
        value_field="score",
        max_slices=6,
    ),
    "risk_return_scatter": _chart(
        component="ScatterChart",
        chart_type="scatter",
        required_fields=["ticker", "annualized_volatility_percent", "annualized_return_percent"],
        required_context=["price_history"],
        fallback_computation="compute_return_and_volatility_from_adjusted_close",
        allowed_intents=["plot_only", "risk_governance", "diversification"],
        blocked_intents=["advisory_allocation", "optimization", "data_quality_only"],
        x_axis="annualized_volatility_percent",
        y_axis="annualized_return_percent",
        point_id="ticker",
        color_axis="sector",
        x_unit="%",
        y_unit="%",
    ),
    "cvar_return_scatter": _chart(
        component="ScatterChart",
        chart_type="scatter",
        required_fields=["ticker", "cvar_95_percent", "annualized_return_percent"],
        required_context=["price_history"],
        fallback_computation="compute_cvar_and_return_from_returns",
        allowed_intents=["plot_only", "risk_governance"],
        blocked_intents=["advisory_allocation", "optimization", "data_quality_only"],
        x_axis="cvar_95_percent",
        y_axis="annualized_return_percent",
        point_id="ticker",
        color_axis="sector",
        x_unit="%",
        y_unit="%",
    ),
    "drawdown_return_scatter": _chart(
        component="ScatterChart",
        chart_type="scatter",
        required_fields=["ticker", "max_drawdown_percent", "annualized_return_percent"],
        required_context=["price_history"],
        fallback_computation="compute_drawdown_and_return_from_price_history",
        allowed_intents=["plot_only", "risk_governance"],
        blocked_intents=["advisory_allocation", "optimization", "data_quality_only"],
        x_axis="max_drawdown_percent",
        y_axis="annualized_return_percent",
        point_id="ticker",
        color_axis="sector",
        x_unit="%",
        y_unit="%",
    ),
    "beta_return_scatter": _chart(
        component="ScatterChart",
        chart_type="scatter",
        required_fields=["ticker", "beta", "annualized_return_percent"],
        required_context=["price_history", "benchmark_series"],
        fallback_computation="compute_beta_if_benchmark_exists",
        allowed_intents=["plot_only", "risk_governance"],
        blocked_intents=["advisory_allocation", "optimization", "data_quality_only"],
        x_axis="beta",
        y_axis="annualized_return_percent",
        point_id="ticker",
        color_axis="sector",
        x_unit="beta",
        y_unit="%",
    ),
    "allocation_vs_risk_contribution_scatter": _chart(
        component="ScatterChart",
        chart_type="scatter",
        required_fields=["ticker", "allocation_percent", "risk_contribution_percent"],
        required_context=["weights", "covariance_matrix"],
        fallback_computation="compute_risk_contribution_from_weights_and_covariance",
        allowed_intents=["plot_only", "risk_governance", "diversification"],
        blocked_intents=["advisory_allocation", "optimization", "data_quality_only"],
        x_axis="allocation_percent",
        y_axis="risk_contribution_percent",
        point_id="ticker",
        color_axis="sector",
        x_unit="%",
        y_unit="%",
    ),
    "bubble_risk_return": _chart(
        chart_tier=CHART_TIER_PRO,
        component="ScatterChartPro",
        chart_type="bubble_scatter",
        required_fields=[
            "ticker",
            "annualized_volatility_percent",
            "annualized_return_percent",
            "bubble_size_value",
            "sector",
        ],
        required_context=["price_history", "weights"],
        fallback_computation="compute_bubble_size_from_weight_or_risk_contribution",
        allowed_intents=["plot_only", "risk_governance", "diversification"],
        blocked_intents=["advisory_allocation", "optimization", "data_quality_only"],
        fallback_chart="risk_return_scatter",
        x_axis="annualized_volatility_percent",
        y_axis="annualized_return_percent",
        point_id="ticker",
        color_axis="sector",
        size_axis="bubble_size_value",
        x_unit="%",
        y_unit="%",
    ),
    "scatter_with_regression_line": _chart(
        component="ScatterChart",
        chart_type="scatter_regression",
        required_fields=["date", "x_return_percent", "y_return_percent"],
        optional_fields=["regression_slope", "regression_intercept", "r_squared"],
        required_context=["price_history", "at_least_two_tickers"],
        fallback_computation="compute_ols_regression",
        allowed_intents=["plot_only", "correlation_covariance", "eda"],
        blocked_intents=["advisory_allocation", "optimization", "data_quality_only"],
        x_axis="x_return_percent",
        y_axis="y_return_percent",
        point_id="date",
        x_unit="%",
        y_unit="%",
    ),
    "ownership_overlap_correlation_scatter": _chart(
        component="ScatterChart",
        chart_type="scatter",
        required_fields=["ticker_pair", "ownership_overlap", "return_correlation"],
        required_context=["institutional_ownership_graph", "price_history"],
        fallback_computation="compute_pairwise_correlation_if_graph_overlap_exists",
        allowed_intents=["plot_only", "graph_contagion", "correlation_covariance"],
        blocked_intents=["advisory_allocation", "optimization", "data_quality_only"],
        x_axis="ownership_overlap",
        y_axis="return_correlation",
        point_id="ticker_pair",
        x_unit="decimal",
        y_unit="decimal",
    ),
    "premium_webgl_scatter": _chart(
        chart_tier=CHART_TIER_PREMIUM,
        component="ScatterChartPremium",
        chart_type="webgl_scatter",
        requires_premium=True,
        required_fields=["id", "x", "y"],
        required_context=["large_scatter_dataset"],
        fallback_chart="risk_return_scatter",
        allowed_intents=["plot_only"],
        blocked_intents=["advisory_allocation", "optimization"],
        x_axis="x",
        y_axis="y",
        point_id="id",
    ),
}


def normalize_plot_id(plot_id: str | None) -> str:
    value = str(plot_id or "").strip().lower()
    value = re.sub(r"^plot_\d+_", "", value)
    value = re.sub(r"[^a-z0-9]+", "_", value)
    return value.strip("_")


def get_chart_definition(plot_id: str | None) -> dict[str, Any] | None:
    return CHART_REGISTRY.get(normalize_plot_id(plot_id))


def premium_charts_enabled() -> bool:
    raw = os.getenv("ENABLE_MUI_PREMIUM_CHARTS") or os.getenv("VITE_ENABLE_MUI_PREMIUM_CHARTS")
    return str(raw or "").strip().lower() in {"1", "true", "yes", "on"}


def premium_unavailable_message(fallback_chart: str | None) -> str:
    if fallback_chart:
        return f"This chart requires MUI X Premium. Rendering fallback chart {fallback_chart} instead."
    return "This chart requires MUI X Premium and no fallback chart is configured."
