export const BAR_CHART_REGISTRY = {
  ticker_concentration_plot: {
    title: 'Ticker Concentration',
    x_axis: 'allocation_percent',
    y_axis: 'ticker',
    unit: 'percent',
    sort: 'descending',
    preferredMode: 'horizontal',
    requiredFields: ['ticker', 'allocation_percent'],
    interpretation: 'Shows whether individual ticker exposures exceed advisory concentration thresholds.',
  },
  sector_concentration_plot: {
    title: 'Sector Concentration',
    x_axis: 'allocation_percent',
    y_axis: 'sector',
    unit: 'percent',
    sort: 'descending',
    preferredMode: 'horizontal',
    requiredFields: ['sector', 'allocation_percent'],
  },
  hhi_concentration_index: {
    title: 'HHI Concentration Index',
    x_axis: 'portfolio',
    y_axis: 'hhi',
    unit: 'ratio',
    requiredFields: ['portfolio', 'hhi'],
  },
  effective_number_of_holdings: {
    title: 'Effective Number of Holdings',
    x_axis: 'portfolio',
    y_axis: 'effective_holdings',
    unit: 'count',
    requiredFields: ['portfolio', 'effective_holdings'],
  },
  current_vs_advisory_allocation_by_ticker: {
    title: 'Current vs Advisory Allocation by Ticker',
    x_axis: 'ticker',
    y_axis: 'allocation_percent',
    unit: 'percent',
    preferredMode: 'grouped',
    requiredFields: ['ticker', 'current_allocation_percent', 'advisory_allocation_percent'],
  },
  current_vs_advisory_sector_allocation: {
    title: 'Current vs Advisory Sector Allocation',
    x_axis: 'sector',
    y_axis: 'allocation_percent',
    unit: 'percent',
    preferredMode: 'grouped',
    requiredFields: ['sector', 'current_allocation_percent', 'advisory_allocation_percent'],
  },
  allocation_change_by_ticker: {
    title: 'Allocation Change by Ticker',
    x_axis: 'ticker',
    y_axis: 'allocation_change_percent',
    unit: 'percent',
    preferredMode: 'diverging',
    sort: 'descending',
    requiredFields: ['ticker', 'allocation_change_percent'],
  },
  risk_contribution_by_ticker: {
    title: 'Risk Contribution by Ticker',
    x_axis: 'risk_contribution_percent',
    y_axis: 'ticker',
    unit: 'percent',
    sort: 'descending',
    preferredMode: 'horizontal',
    requiredFields: ['ticker', 'risk_contribution_percent'],
  },
  allocation_vs_risk_contribution: {
    title: 'Allocation vs Risk Contribution',
    x_axis: 'ticker',
    y_axis: 'percent',
    unit: 'percent',
    preferredMode: 'grouped',
    requiredFields: ['ticker', 'allocation_percent', 'risk_contribution_percent'],
  },
  cvar_comparison: {
    title: 'CVaR Comparison',
    x_axis: 'strategy',
    y_axis: 'cvar_95',
    unit: 'percent',
    requiredFields: ['strategy', 'cvar_95'],
  },
  maximum_drawdown_comparison: {
    title: 'Maximum Drawdown Comparison',
    x_axis: 'strategy',
    y_axis: 'maximum_drawdown',
    unit: 'percent',
    requiredFields: ['strategy', 'maximum_drawdown'],
  },
  sharpe_ratio_comparison: {
    title: 'Sharpe Ratio Comparison',
    x_axis: 'strategy',
    y_axis: 'sharpe_ratio',
    unit: 'ratio',
    requiredFields: ['strategy', 'sharpe_ratio'],
  },
  eigenvector_centrality_by_ticker: {
    title: 'Eigenvector Centrality by Ticker',
    x_axis: 'centrality',
    y_axis: 'ticker',
    unit: 'decimal',
    preferredMode: 'horizontal',
    sort: 'descending',
    requiredFields: ['ticker', 'centrality'],
  },
  contagion_penalty_score: {
    title: 'Contagion Penalty Score',
    x_axis: 'ticker',
    y_axis: 'penalty_score',
    unit: 'decimal',
    sort: 'descending',
    requiredFields: ['ticker', 'penalty_score'],
  },
  strategy_performance_comparison: {
    title: 'Strategy Performance Comparison',
    x_axis: 'strategy',
    y_axis: 'metric_value',
    unit: 'percent',
    preferredMode: 'grouped',
    requiredFields: ['strategy'],
  },
};

export function getBarChartDefinition(plotId) {
  return BAR_CHART_REGISTRY[plotId] || null;
}
