import { CHART_TIER } from '../chartTierConfig.js';

export const SCATTER_CHART_TYPES = new Set(['scatter', 'bubble_scatter', 'scatter_regression', 'webgl_scatter']);

function defineScatterChart(config) {
  return {
    plot_id: config.plot_id,
    chart_type: config.chart_type || 'scatter',
    chart_tier: config.chart_tier || CHART_TIER.FREE,
    component: config.component || 'ScatterChart',
    requires_premium: Boolean(config.requires_premium),
    required_fields: config.required_fields || [],
    optional_fields: config.optional_fields || [],
    required_context: config.required_context || [],
    fallback_computation: config.fallback_computation || null,
    allowed_intents: config.allowed_intents || [],
    blocked_intents: config.blocked_intents || ['advisory_allocation', 'optimization'],
    fallback_chart: config.fallback_chart || null,
    x_axis: config.x_axis,
    y_axis: config.y_axis,
    point_id: config.point_id || 'ticker',
    color_axis: config.color_axis || null,
    size_axis: config.size_axis || null,
    x_unit: config.x_unit || 'none',
    y_unit: config.y_unit || 'none',
    ...config,
  };
}

export const SCATTER_CHART_REGISTRY = {
  risk_return_scatter: defineScatterChart({
    plot_id: 'risk_return_scatter',
    title: 'Risk-Return Scatter by Ticker',
    required_fields: ['ticker', 'annualized_volatility_percent', 'annualized_return_percent'],
    required_context: ['price_history'],
    fallback_computation: 'compute_return_and_volatility_from_adjusted_close',
    x_axis: 'annualized_volatility_percent',
    y_axis: 'annualized_return_percent',
    point_id: 'ticker',
    color_axis: 'sector',
    x_unit: '%',
    y_unit: '%',
  }),
  cvar_return_scatter: defineScatterChart({
    plot_id: 'cvar_return_scatter',
    title: 'CVaR-Return Scatter by Ticker',
    required_fields: ['ticker', 'cvar_95_percent', 'annualized_return_percent'],
    fallback_computation: 'compute_cvar_and_return_from_returns',
    x_axis: 'cvar_95_percent',
    y_axis: 'annualized_return_percent',
    point_id: 'ticker',
    color_axis: 'sector',
    x_unit: '%',
    y_unit: '%',
  }),
  drawdown_return_scatter: defineScatterChart({
    plot_id: 'drawdown_return_scatter',
    title: 'Drawdown-Return Scatter by Ticker',
    required_fields: ['ticker', 'max_drawdown_percent', 'annualized_return_percent'],
    fallback_computation: 'compute_drawdown_and_return_from_price_history',
    x_axis: 'max_drawdown_percent',
    y_axis: 'annualized_return_percent',
    point_id: 'ticker',
    color_axis: 'sector',
    x_unit: '%',
    y_unit: '%',
  }),
  allocation_vs_risk_contribution_scatter: defineScatterChart({
    plot_id: 'allocation_vs_risk_contribution_scatter',
    title: 'Allocation vs Risk Contribution Scatter',
    required_fields: ['ticker', 'allocation_percent', 'risk_contribution_percent'],
    required_context: ['weights', 'covariance_matrix'],
    fallback_computation: 'compute_risk_contribution_from_weights_and_covariance',
    x_axis: 'allocation_percent',
    y_axis: 'risk_contribution_percent',
    point_id: 'ticker',
    color_axis: 'sector',
    x_unit: '%',
    y_unit: '%',
  }),
  bubble_risk_return: defineScatterChart({
    plot_id: 'bubble_risk_return',
    title: 'Risk-Return Bubble by Ticker',
    chart_type: 'bubble_scatter',
    chart_tier: CHART_TIER.PRO,
    component: 'ScatterChartPro',
    required_fields: ['ticker', 'annualized_volatility_percent', 'annualized_return_percent', 'bubble_size_value', 'sector'],
    required_context: ['price_history', 'weights'],
    fallback_computation: 'compute_bubble_size_from_weight_or_risk_contribution',
    fallback_chart: 'risk_return_scatter',
    x_axis: 'annualized_volatility_percent',
    y_axis: 'annualized_return_percent',
    point_id: 'ticker',
    color_axis: 'sector',
    size_axis: 'bubble_size_value',
    x_unit: '%',
    y_unit: '%',
  }),
  scatter_with_regression_line: defineScatterChart({
    plot_id: 'scatter_with_regression_line',
    title: 'Return Regression Scatter',
    chart_type: 'scatter_regression',
    required_fields: ['date', 'x_return_percent', 'y_return_percent'],
    optional_fields: ['regression_slope', 'regression_intercept', 'r_squared'],
    required_context: ['price_history', 'at_least_two_tickers'],
    fallback_computation: 'compute_ols_regression',
    x_axis: 'x_return_percent',
    y_axis: 'y_return_percent',
    point_id: 'date',
    x_unit: '%',
    y_unit: '%',
  }),
  ownership_overlap_correlation_scatter: defineScatterChart({
    plot_id: 'ownership_overlap_correlation_scatter',
    title: 'Ownership Overlap vs Return Correlation',
    required_fields: ['ticker_pair', 'ownership_overlap', 'return_correlation'],
    required_context: ['institutional_ownership_graph', 'price_history'],
    fallback_computation: 'compute_pairwise_correlation_if_graph_overlap_exists',
    x_axis: 'ownership_overlap',
    y_axis: 'return_correlation',
    point_id: 'ticker_pair',
    x_unit: 'decimal',
    y_unit: 'decimal',
  }),
  premium_webgl_scatter: defineScatterChart({
    plot_id: 'premium_webgl_scatter',
    title: 'Premium WebGL Scatter',
    chart_type: 'webgl_scatter',
    chart_tier: CHART_TIER.PREMIUM,
    component: 'ScatterChartPremium',
    requires_premium: true,
    required_fields: ['id', 'x', 'y'],
    required_context: ['large_scatter_dataset'],
    fallback_chart: 'risk_return_scatter',
    x_axis: 'x',
    y_axis: 'y',
    point_id: 'id',
  }),
};

export function getScatterChartDefinition(plotId) {
  return SCATTER_CHART_REGISTRY[String(plotId || '').trim()] || null;
}



